# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20171116_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='compra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
