# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_person_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='venda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
